<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">

        <?php
              // GMT-Block
              $_helper = $this->helper('Magento\Catalog\Helper\Output');
              $_product = $block->getProduct();
              $_call = $block->getAtCall();
              $_code = $block->getAtCode();
              $_className = $block->getCssClass();
              $_attributeLabel = $block->getAtLabel();
              $_attributeType = $block->getAtType();
              $_attributeAddAttribute = $block->getAddAttribute();
              echo '<div class="gmt-produkt-details">';
              echo '<div class="row">';
              echo '<div class="col-md-7"><h2 class="gmt-produkt-details-ueberschrift gmt-produkt-details-beschreibung">Beschreibung</h2>';
              echo $_product->getData('description').'</div>';
              echo '<div class="col-md-5"><h2 class="gmt-produkt-details-ueberschrift gmt-produkt-details-details">&nbsp;<!--Details--></h2>';
              ?>
              <?php $layout = $block->getLayout(); ?>
                    <?php foreach ($detailedInfoGroup as $name):?>
                        <?php
                            $html = $layout->renderElement($name);
                            if (!trim($html)) {
                                continue;
                            }
                            $alias = $layout->getElementAlias($name);
                            $label = $block->getChildData($alias, 'title');

                        ?>
                            <?php /* @escapeNotVerified */ /* additional = eigene attribute*/if ($alias == "additional") echo $html; ?>
                    <?php endforeach;?>
              <?php
              echo '</div>';
              echo '</div></div>'; //gmt-produkt-details + row
              ?>
        <?php  // END:GMT-Block ?>

        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
